[Icon Theme]
Name=Zafiro-icons
Comment=icon theme flat for gnome,xfce and lxde
Comment[es]=tema de iconos planos para gnome,xfce y lxde
Inherits=gnome,hicolor,Numix,breeze

PanelDefault=22
PanelSizes=22

# Directory list
Directories=windowbar,menu-group,misc

[windowbar]
Size=48
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[menu-group]
Size=48
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[misc]
Size=48
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable